version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fcc-aas-proto"
s3_prefix = "fcc-aas-alpha"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
